# _quarto-gh.yml
project:
  render:
    - content/**/*.qmd
  output-dir: _site_gh

website:
  site-url: https://USERNAME.github.io/eLearning-Vagheiten-NFDI/
  title: "ELearning-Modul für Münzdaten"

  navbar:
    background: "#13294B"
    left:
      - text: Mein Fortschritt
        href: content/progress.qmd

  sidebar:
    style: docked
    search: true
    contents:
      - text: "Hauptseite"
        href: content/index.qmd

      - section: "🔍 I. Basiswissen digitale Numismatik"
        href: content/digital_index.qmd
        contents:
          - content/digital_scientific_data.qmd
          - content/digital_fair_data.qmd
          - content/digital_data_access.qmd
          - content/digital_data_aggregation.qmd

      - section: "🌐 II. Vage Münzdaten"
        href: content/vague_index.qmd
        contents:
          - content/vague_definitions.qmd
          - content/vague_solving_vagueness.qmd

  page-navigation: true

format: 
  live-html:
    toc: true
    toc-location: right
    embed-resources: false
    brand: brand/_n4o_brand.yml
    theme: brand/n4o_html.scss