# _quarto.yml
project:
  type: website
  output-dir: _site
  resources: 
    - assets/

profile:
  default: gh

metadata-files:
  - metadata/layout.yml
  - metadata/autor_innen.yml
  - metadata/oer_metadata.yml

format: 
  live-html:
    toc: true
    toc-location: right
    embed-resources: false
    brand: brand/_n4o_brand.yml
    theme: brand/n4o_html.scss