# _quarto-numiscience.yml
project:
  pre-render: python scripts/split_pages.py
  render:
    - numiscience/**/*.qmd
  output-dir: _site_numiscience

website:
  site-url: https://USERNAME.github.io/eLearning-Vagheiten-NFDI/numiscience/

  # strip navigation
  sidebar: false
  navbar: false
  page-navigation: false