# _quarto-numiscience.yml
project:
  pre-render: py scripts/split_pages.py
  output-dir: _site/numiscience

website:
  site-url: https://USERNAME.github.io/eLearning-Vagheiten-NFDI/numiscience/

  # strip navigation
  sidebar: false
  navbar: false
  page-navigation: false