project:
  type: website
  output-dir: _site
  resources: 
    - assets/

metadata-files:
  - layout.yml
  - autor_innen.yml
  - oer_metadata.yml

website:
  title:  "ELearning-Modul für Münzdaten"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: Hauptseite
        href: content/index.qmd
      - text: "Lektion 1: Datenzugang"
        href: content/data_access.qmd
      - text: "Lektion 2: Datenverarbeitung"
        href: content/data_aggregation.qmd
      - text: "was ist NFDI"
        href: content/nfdi.qmd