---
title: "Hauptseite der Übung"
subtitle: "neuer Untertitel"
lang: de
date: today
date-modified: last-modified
date-format: "DD.MM.YYYY"
metadata-files: 
 - ../layout.yml
 - ../autor_innen.yml
 - ../oer_metadata.yml
# filters: # tbd: Export-Filter für Metadaten-Dumps (OERSI etc.)
#  - filters/export_alle_metadaten.lua
#  - filters/export_oersi.lua
# export_alle_metadaten:
#  mode: schema
#  exclude: [format, filters, brand, from, metadata-files, export-meta, export-meta-dir]
---

## Praktische Bezüge/Anwendungsbeispiel/Motivation

Holen Sie die Lernenden in diesem Absatz ab. Stellen Sie in wenigen Sätzen, mit Beispielen und Fragen das Thema der Übung vor.

## Lernziele

In diesem Skript lernen Sie:

- Ziel 1
- Ziel 2

Idealerweise beziehen sie sich in dieser Aufzählung auf die Lernzielmatrix zum Themenbereich Forschungsdatenmanagement (FDM) für die Zielgruppen Studierende, PhDs und Data Stewards.^[Petersen, B., Engelhardt, C., Hörner, T., Jacob, J., Kvetnaya, T., Mühlichen, A., Schranzhofer, H., Schulz, S., Slowig, B., Trautwein-Bruns, U., Voigt, A., & Wiljes, C. (2023). Lernzielmatrix zum Themenbereich Forschungsdatenmanagement (FDM) für die Zielgruppen Studierende, PhDs und Data Stewards. Zenodo. [https://doi.org/10.5281/zenodo.8010617](https://doi.org/10.5281/zenodo.8010617)]

## Voraussetzungen

Für das erfolgreiche Absolvieren dieser Übung wird vorausgesetzt:

- Voraussetzung 1

Versuchen sie so detailliert wie möglich die Voraussetzungen für die Durchführung der Übung aufzuzählen. Geben sie Hinweise, wo die Lernenden entsprechende/s Kompetenzen/Wissen erwerben können. Verweisen sie insbesondere auf Hilfestellungen für die Software-Installation und Tutorials zum Umgang.

## Datengrundlage

Erläutern und verlinken sie die Datengrundlage für die Übung.

## Vorbereitung

## Durchführung

## Ergebnisse

## Transferaufgaben (optional)

Stellen sie weiterführende Aufgaben, in denen die Lernenden die erworbenen Kenntnisse in andere Kontexte transferieren können.

## Lösungen (optional)

Stellen Sie Aufgaben und Lösungen noch einmal systematisch zusammen.

## Weiterführende Quellen und Informationen

Der Ort für weiterführende Quellen und Informationen. Wenn Sie Fußnoten im Text eingefügt haben, werden die bibliographischen Angaben automatisch generiert und in das Dokument eingefügt.

## Nachnutzen {.appendix}

Alle sind herzlich eingeladen, diesen Baustein und die zugehörige Copyleft-Lizenz zu nutzen, um ihr Wissen und Expertise in die Verbesserung und Aktualisierung einzubringen. Alle können die Inhalte erweitern oder überarbeiten, zum Beispiel um Anwendungsszenarien und Nutzungskontexte zu erweitern.

Unser Wunsch ist ein lebendiges, stetig wachsendes Dokument, das sich durch die Beiträge vieler verändert - im Einklang mit eines sich wandelnden Umfelds. Wir freuen uns im Falle einer Überarbeitung über eine kurze Notiz – das ist aber selbstverständlich keine Pflicht.

:link: [Dieser Baustein als Website:]({{< meta site-url >}})

:link: [Quarto-Quellcode dieses Bausteins:]({{< meta repo-url >}})

