---
title: "Forschungsdaten"
lang: de
date: today
date-modified: last-modified
date-format: "DD.MM.YYYY"
title-block: None 
---

## Was sind numismatische Forschungsdaten?
Forschungsdaten sind zunächst jede Art von digitalen Daten, die wissenschaftlich ausgewertet werden können. Sie sind Grundlage und Ergebnis wissenschaftlicher Arbeit.

Es gibt sehr viele numismatische Daten und mehrere Datenbanken, die über 100.000 Stücke enthalten. Für jede Münze, egal aus welcher Zeit oder Region, gibt es eine fixe Anzahl relevanter Datenfelder. Häufig gehören zu diesen Münzdaten auch Bilder der [Averse](https://de.wikipedia.org/wiki/Avers_(Numismatik)) und [Reverse](https://de.wikipedia.org/wiki/Revers_(Numismatik))  


Alle der folgenden Münzen aus unterschiedlichen Epochen haben beispielsweise das Informationen zu Material, Dargestellten, Prägestätten. Auch wenn die Euromünze keine dargestellte Person hat und die Prägestätte der Münze von Napoleon III. unbekannt ist, kann auch gerade das Nichtvorhandensein dieser Informationen wichtig für die Interpretation der Münzdaten sein. 

```{python}
#| echo: false
import matplotlib.pyplot as plt
from matplotlib.offsetbox import OffsetImage, AnnotationBbox
from pathlib import Path
from PIL import Image

# --- Configuration ---
images_dir = Path.cwd().parent / "assets" / "img"
images = [images_dir / "image_athens.jpg", images_dir /"image_napoleon.png", images_dir / "image_euro.jpg"]

image_positions = [1, 3, 5]
image_y = 2

# Attributes as single entries
attributes_data = [
    {"name": "Prägestätte", "x": 0.5, "y": 3.5, "direction": 1, "connected_to": [0,2]},
    {"name": "Dargestellte", "x": 4, "y": 3.5, "direction": 1, "connected_to": [0,1]},
    {"name": "Datierung", "x": 1, "y": 0.5, "direction": -1, "connected_to": [0,1,2]},
    {"name": "Material", "x": 3, "y": 0.5, "direction": -1, "connected_to": [0,1,2]}
]

# --- Helper ---
def load_img(path, size=(150, 150)):
    img = Image.open(path).convert("RGBA")
    img = img.resize(size, Image.LANCZOS)
    return OffsetImage(img, zoom=1)

# --- Figure ---
fig, ax = plt.subplots(figsize=(8,4))
ax.axis('off')

# Draw images
for x, img_path in zip(image_positions, images):
    ab = AnnotationBbox(load_img(img_path), (x, image_y), frameon=False)
    ax.add_artist(ab)

# Draw attributes and arrows
for attr in attributes_data:
    # Draw attribute node
    ax.text(attr["x"], attr["y"], attr["name"], ha='center', va='center', fontsize=10,
            bbox=dict(boxstyle="round,pad=0.4", facecolor="#F97307", edgecolor="#555555"))
    
    # Draw arrows from connected images
    for img_idx in attr["connected_to"]:
        img_x = image_positions[img_idx]
        ax.annotate("", xy=(attr["x"], attr["y"] - 0.15*attr["direction"]),
                    xytext=(img_x, image_y + 0.2*attr["direction"]),
                    arrowprops=dict(arrowstyle="-|>", color="#555555", lw=1.2))

# Layout
plt.xlim(0,6)
plt.ylim(0,4)
plt.tight_layout()
plt.show()
```
: Münzen und ihre Datenfelder {#tbl-muenzdaten tbl-colwidths="[20,10,10,20]"}
Links: https://ikmk.smb.museum/object?id=18214977 
Mitte: https://nat.museum-digital.de/object/73659
Rechts: https://ikmk.smb.museum/object?id=18203837
############ TODO: Wie sinnvoll hier zitieren



::: {.callout-note}
Dieses Bild wurde nicht händisch in einem Bildbearbeitungsprogramm erstellt. Es wurde direkt in Python programmiert und nutzt die Daten, die direkt aus den Münzdatenbanken kommen. Am Ende dieses und des nächsten Moduls können wir Schaubilder wie das obere mit Münzen aus verschiedenen Datenbanken selbst erstellen. 
:::

## Wie können wir uns Münzdaten vorstellen

Die einfachste Form, Münzdaten strukturiert zu speichern, ist eine Tabelle. Die Reihen stehen für die einzelne Münze, die Spalten für bestimmte Kategorien, die für die Münze erfasst werden. Das folgende Beispiel zeigt dabei, dass eine Tabelle für Münzdaten nicht ausreicht. 


| Name | Gewicht| Durchmesser | Webportal
|---------|:-----|-----|-----|
| https://ikmk.smb.museum/object?id=18201393      | 5,10mm     | 20g  | http://numismatics.org/ocre/id/ric.5.post.29 |

: Münzdaten in tabellarischer Form {#tbl-muenzdaten tbl-colwidths="[15,10,10,15]"}

Das Feld Name weißt dabei eindeutig auf den Aureus des Postumus hin, die mit der Objektnummer: 18201393 beim Münzkabinett der Staatlichen Museen Berlin liegt. Diese Münze hat unter anderem ein spezifisches Gewicht und einen spezifischen Durchmesser. Außerdem gibt häufig Literatur zu einzelnen Münzen, so genannte Typenkataloge, die einzelnen Münzserien (Typen) beschreiben. Im vorliegenden Fall ist das der Typ Roman Imperial Coinage Band 5, Postumus, Nummer 29.
 
::: {.callout-note collapse="true"}
## Was sind Typenkataloge?
Typenkataloge sind in der Numismatik seit dem 19. Jahrhundert die bevorzugte Art, Münzen zu ordnen. Maßstäbe setzten die British Museum Coinage (BMC) und darauf aufbauend Roman Imperial Coinage (RIC). Diese Bände enthalten alle bekannten Münzen der Zeit und alle für die [Münzbestimmung](https://pecunia.zaw.uni-heidelberg.de/NumiScience/muenzbestimmung) notwendigen Felder. Bei der digitalisierung der Kataloge wurden die Bilder und technischen Daten von Münzen direkt mit dem Eintrag verknüpft, was die Bestimmung erleichtert.
:::

Es ergibt Sinn, die Informationen, die die Münze mit anderen Münzen des gleichen Typs teiltm Münztyp zugeordnet werden, in einer eigenen Tabelle zu speichern. Einerseits kann so die Herkunft der Daten verstanden werden, andererseits können Anpassungen zentral vorgenommen werden. Häufig sind Nutzer einer Datenbank auch an weiterführenden Informationen zu mit den Münzen verknüpften Orten oder Personen interessiert. Auch für diese Informationen sollten eigene Tabellen erstellt werden, damit die Daten zentralisiert verändert werden können. So erhalten die Münzdaten komplexe Vernetzungen.


### Übung 2: Mit einer Typreferenz verknüpfte Daten herausfinden
Navigieren Sie in einem neuen Tab zu einem Referenzportal wie [CRRO](http://numismatics.org/crro), [OCRE](http://numismatics.org/ocre) oder [Pella](http://numismatics.org/pella). Suchen Sie darin nach einem Münztyp und nach einer Münze. Geben sie beide in die folgende Python-Zelle ein und führen Sie sie aus.

### TODO kleines GUIDE wo lassen sich Münztypen finden

Wie verändert sich die Tabelle, je nachdem ob Sie eine URL zu einem Münztyp oder zu einer Münze eingegeben haben? Prüfen Sie den jeweiligen Output und überlegen Sie, warum es Sinn ergibt, warum die Daten in den jeweiligen Tabellen gespeichert sind.


```{pyodide}
#| envir: coin_data
#| exercise: ex_2
url = "" # <------ Hier URL zwischen die Anführungszeichen (!) einfügen


from pyodide.http import pyfetch
import pandas as pd
import urllib.parse
from IPython.display import display, HTML

raw_query = f"SELECT ?predicate ?object WHERE {{ <{url}> ?predicate ?object . }}"
safe_query = urllib.parse.quote(raw_query)
api_url = f"https://nomisma.org/query?query={safe_query}&output=json"

# 4. Fetch
res = await pyfetch(api_url, method="GET")
if res.status == 200:
    data = await res.json()
    rows = []
    for r in data['results']['bindings']:
        p = r['predicate']['value'].split('/')[-1].split('#')[-1]
        o = r['object']['value'].split('/')[-1].split('#')[-1]
        rows.append({"Attribute": p, "Value": o})
    df = pd.DataFrame(rows)
    pd.set_option('display.max_colwidth', None)
    display(HTML(f"<h3>Source: <a href='{url}' target='_blank'>{url}</a></h3>"))
    display(HTML(df.to_html(index=False)))
```


### Was sind Graphen?

Sobald Münzdaten aus komplexen Verbindungen verschiedener Datenquellen bestehen, eignet sich eine andere Darstellungsform als Tabellen: Graphen. Bei Graphen gibt es nicht die Tabelle "Münzen" oder "Münztypen", die verschiedene Einträge enthalten. Stattdessen steht die einzelne Münze (über einen eindeutigen Identifikator, siehe forlgender Abschnitt "Normdaten") im Zentrum. Die Münze ist über beschriftete Pfeile mit den ihr zugeordneten Informationen verbunden. Die Beschriftungen der Pfeile entsprechen dabei den Namen der Tabellenspalten. Das können Sie im folgenden Codebeispiel überprüfen, indem Sie ihre URL aus dem vorigen Beispiel einfügen.  

```{pyodide}
#| envir: coin_data

url = ""   # <------ Hier URL zwischen die Anführungszeichen (!) einfügen
depth = 1  # <------ Zeigt die Anzahl der Ebenen im Graph an (akzeptiert Werte 1 und 2)

# ----------------------------------------
from pyodide.http import pyfetch
import urllib.parse
import networkx as nx
import matplotlib.pyplot as plt
root_id = url.split('/')[-1]
raw_query = f"""
SELECT ?s ?p ?o{' ?p1' if depth == 2 else ''} WHERE {{
  {{ BIND(<{url}> AS ?s) . ?s ?p ?o . }}
  {'UNION { <' + url + '> ?p1 ?s . FILTER(isIRI(?s)) . ?s ?p ?o . }' if depth == 2 else ''}
}}
"""

safe_query = urllib.parse.quote(raw_query)
api_url = f"https://nomisma.org/query?query={safe_query}&output=json"

res = await pyfetch(api_url)
if res.status == 200:
    data = await res.json()
    G = nx.DiGraph()

    clean = lambda x: x.split('/')[-1].split('#')[-1]

    for r in data["results"]["bindings"]:
        s = clean(r["s"]["value"])
        p = clean(r["p"]["value"])
        o = clean(r["o"]["value"])

        if depth == 2 and "p1" in r:
            p1 = clean(r["p1"]["value"])
            if p1 in ["hasCollection", "inDataset"]:
                continue

        G.add_edge(s, o, label=p)

    plt.figure(figsize=(14, 9))
    pos = nx.spring_layout(G, k=0.6)
    colors = ["orange" if n == root_id else "skyblue" for n in G.nodes()]

    nx.draw(G, pos, with_labels=True,
            node_color=colors, node_size=1800,
            font_size=8, edge_color="silver", arrowsize=12)

    nx.draw_networkx_edge_labels(
        G, pos,
        edge_labels=nx.get_edge_attributes(G, "label"),
        font_size=7
    )
    plt.show()
```

Diese Darstellungsweise erleichtert die Beantwortung von komplexen Fragestellungen


Man nehme die Fragestellung: In einem Münzfund wurden zahlreiche Münzen unterschiedlicher römischer Kaiser gefunden. Uns interessiert, ob diese Münzen eher am Anfang oder am Ende der Regierungszeit der jeweiligen Kaiser geprägt wurden. 

### Was ist eine Ontologie?

Wenn Daten auf als Graphen dargestellt werden, zeigt sich unmittelbar, welche Elemente durch eine Ontologie standardisiert werden können. „Ontologie“ ist ursprünglich ein Begriff aus der Philosophie. Er stammt aus dem Griechischen und kann mit der „Lehre des Seins“ übersetzt werden. In der Informatik meint der Begriff aber eine solche Systematisierung von Begrifflichkeiten und deren Abhängigkeiten voneinander. Diese Standardisierung ist in der Numismatik bereits weitgehend abgeschlossen. International gültig ist die [Nomisma Ontology](http://www.nomisma.org/ontology). Auf diese Weise hat jede Münze unabhängig von der Sprache der Erfasser eine standardisiertes Datenfeld.  
Kommen Ihnen die Namen in der Ontologie von Nomisma bekannt vor? Es sind die gleichen Variablennamen, die in der Tabelle und im Graph angezeigt werden.

Die Nomisma Ontology differenziert nach Objekten und Typen, die jeweils andere Datenfelder haben. So werden die Informationen effektiv nur dort gespeichert, wo sie dazu gehören. 
Die Graphdarstellung hilft auch, die Informationen aus Typenportalen separat zu speichern und mit dem Datensatz zu verknüpfen. die mit der Münze verknüpfte OCRE-ID hat beispielsweise ebenfalls einen Graph.

### Was sind Normdaten?


Bei Münzen gibt es also eine Liste an Datenfeldern, die immer vorhanden sind. In den meisten Datenbanken werden diese Datenfelder normiert erfasst. (LINK oder Erklärfenster Normierung / Normdaten) Auch diese sind in der Ontologie von Nomisma hinterlegt. Sie haben den Typ Class, die Prädikate haben den Typ Property und haben immer ein has vor dem Text. 
